# training:
epochs: 1000
batch_size: 32
learning_rate: 0.0003 #1e-4
weight_decay: 0.00001 #1e-5
# data:
dataset: fred_md
# transform:
use_stft: true
n_fft: 63
hop_length: 23
# model:
img_resolution: 32
input_channels: 2
unet_channels: 128
ch_mult: [1,2,4,4]
attn_resolution: [32,16,8]
diffusion_steps: 18
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
