# training:
epochs: 1000
batch_size: 16
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
# data:
dataset: kdd_cup
use_stft: true
# transform:
n_fft: 223
hop_length: 98
# model:
img_resolution: 112
input_channels: 2
unet_channels: 128
ch_mult: [1,2,4,4]
attn_resolution: [28,14]
diffusion_steps: 18
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
