# training:
epochs: 1000
batch_size: 128
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
# data:
dataset: sine
seq_len: 24
# transform:
use_stft: false
delay: 3
embedding: 8
# model:
img_resolution: 8
input_channels: 5
unet_channels: 128
ch_mult: [1,2,2,2]
attn_resolution: [8,4,2]
diffusion_steps: 18
ema: true
ema_warmup: 100
# logging:
logging_iter: 100

