# training:
epochs: 1000
batch_size: 8
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
# data:
dataset: traffic_hourly
# transform:
use_stft: false
delay: 136
embedding: 144
# model:
img_resolution: 144
input_channels: 1
unet_channels: 128
ch_mult: [1,2,4,4]
attn_resolution: [36,18]
diffusion_steps: 18
ema: true
ema_warmup: 100
# logging:
logging_iter: 100

