# training:
epochs: 1000
batch_size: 8
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
task: interpolation
mask_rate: 0 # physionet and USHCN are sparse datasets that uses their own masking.
  # Please see  https://github.com/boschresearch/Continuous-Recurrent-Units for more information.
# data:
dataset: climate
csv_file_path: small_chunked_sporadic.csv
sample_tp: null
cut_tp: null
T_val: 150
max_val_samples: 3
dir: ./data/long_range/climate/small_chunk_fold_idx_0/
base: ./data/long_range/climate/
# transform:
use_stft: false
delay: 42
embedding: 48
# model:
img_resolution: 48
input_channels: 5
unet_channels: 128
ch_mult: [1,2,4,4]
attn_resolution: [32,16,8]
diffusion_steps: 18
ema: true
ema_warmup: 100
# logging:
logging_iter: 100

